_target_: src.systems.mi_mamba.MIMambaSystem
model_cfg:
  _target_: src.models.mi_mamba.MIMamba
#  video_encoder_path: "./model_weight/echo_prime_encoder.pt"
#  frozen_encoder: true
  in_chans: 3
  num_classes: 2
  depths: [2, 2, 2, 2]
  feat_size: [16, 32, 64, 128]
#  feat_size: [48, 96, 192, 384]
  drop_path_rate: 0
  layer_scale_init_value: 1e-6
  hidden_size: 768
  norm_name: "instance"
  conv_block: true
  res_block: true
  spatial_dims: 3
  dropout_rate: 0.5
learning_rate: 1e-5
