_target_: src.systems.mi_mamba_cross_ssm_system.MIMambaCrossSSMSystem
model_cfg:
  _target_: src.models.mi_mamba_cross_ssm_model.DualMIMamba_CrossSSM
  in_chans: 3
  num_classes: 1
  depths: [2, 2, 2, 2]
  feat_size: [16, 32, 64, 128]
#  feat_size: [48, 96, 192, 384]
  drop_path_rate: 0
  layer_scale_init_value: 1e-6
  hidden_size: 768
  norm_name: "instance"
  res_block: true
  spatial_dims: 3
  dropout_rate: 0.5

learning_rate: 1e-5
