_target_: src.systems.single_view_system.SingleViewSystem
model_cfg:
  _target_: src.models.single_view_model.SingleViewModel
  video_encoder_path: "./model_weight/echo_prime_encoder.pt"
  frozen_encoder: true
learning_rate: 1e-5
